sudo: required
services:
  - docker

before_install:
  - docker build -t srodge1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run srodge1/react-test npm test -- --coverage

after_success:
  - docker build -t srodge1/multi-client ./client
  - docker build -t srodge1/multi-nginx ./nginx
  - docker build -t srodge1/multi-server ./server
  - docker build -t srodge1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing these images to the docker hub
  - docker push srodge1/multi-client
  - docker push srodge1/multi-nginx
  - docker push srodge1/multi-worker
  - docker push srodge1/multi-server
